task: 'wild'
subject: '0010_04'
experiment: 'single_gpu'

root_path: '/vision/u/xtiange/human/nerf/humannerf'
include_img: True
##############################################3
## Network Specs

# non-rigid motion mlp
non_rigid_motion_mlp:
  kick_in_iter: 100000
  full_band_iter: 200000

# pose decoder
pose_decoder:
  kick_in_iter: 999999

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_train'

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_test'

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'monocular_test'

allview:
  dataset_module: 'core.data.human_nerf.allview'
  dataset: 'monocular_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'monocular_test'

backview:
  dataset_module: 'core.data.human_nerf.backview'
  dataset: 'monocular_test'


bgcolor: [255., 255., 255.]
resize_img_scale: 0.25
#crop_image_scale: [1200, 1200]

# crop: [300, 1300, 500, 1300]

bbox_offset: 2.0 # 0.15 for training

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 32      # [Patch] size of patch
