task: 'wild'
subject: 'h36m'
experiment: 'gridnet'

network_module: 'core.nets.human_nerf.gridnet'

root_path: '/vision/u/xtiange/human/nerf/humannerf'



canonical_mlp:
  module: 'core.nets.human_nerf.canonical_mlps.grid_rgb_sigma'
  mlp_depth: 4        # layers in network
  mlp_width: 128       # channels per layer
  multires: 10         # log2 of max freq for positional encoding (3D location)
  i_embed: 0           # set 0 for default positional encoding, -1 for none

##############################################3
## Network Specs

# non-rigid motion mlp
non_rigid_motion_mlp:
  kick_in_iter: 1000000
  full_band_iter: 2000000

# pose decoder
pose_decoder:
  kick_in_iter: 5000

##############################################3
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_train'
  maxiter: 200000

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_test'
  dump_interval: 1000

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'monocular_test'

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'monocular_test'

allview:
  dataset_module: 'core.data.human_nerf.allview'
  dataset: 'monocular_test'

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'monocular_test'

backview:
  dataset_module: 'core.data.human_nerf.backview'
  dataset: 'monocular_test'


bgcolor: [255., 255., 255.]
resize_img_scale: 0.5

bbox_offset: 0.35 # 0.15 for training

# reduce the size of patch from 32x32 to 20x20 to fit in a single gpu
patch:
  size: 32      # [Patch] size of patch
